### ISSUE TITLE
Honey Fluid Cow makes bucket disappear

### ISSUE THREAD

**Issue by Cynix32** [lazyMods/RandomFluidCows#1] opened 2021-08-20 00:05 UTC
Using Java 8 Runtime
Forge 36.2.2
MC 1.16.5

When a honey fluid cow spawns. it does not provide a honey bucket. Using the honey bucket on it just causes the bucket to literally vanish.

Referencing an earlier comment on CurseForge saying that thermal series does not have a honey fluid, I hope these screenshots are more than enough proof that Thermal Series does indeed add a honey fluid.

![2021-08-20_08 03 46](https://user-images.githubusercontent.com/69455883/130159178-28b40c1f-c674-4c74-95a6-eefde80123ef.png)

![2021-08-20_08 04 16](https://user-images.githubusercontent.com/69455883/130159200-18837570-f9f0-4f00-a7eb-a5b172278ade.png)

**Comment by Cynix32** [comment] 2021-08-20 00:38
Here is a recording:
https://youtu.be/UQHq5mr4fY4

**Comment by lazynessmind** [comment] 2021-08-20 11:26
Hi. Indeed Thermal series has a Honey Fluid but is present on the CofhCore library mod.
The disappearing Bucket is a bug in Random Fluid Cows and the cause is the fact that CofhCore fluids don't have a bucket version for the Fluids. 
The bug is fixed in f47edb6, but your honey cow can't give you a Honey Bucket because the game doesn't have one.

I have two solutions for these problems:
* I remove all the fluids that don't have a Bucket version and the game won't spawn cows with that fluid;
* I add buckets when the fluid doesn't have one.

Let me know what is the best solution for your case.
Meanwhile, I will open an issue to know if it's supposed to have a bucket version of Honey in CoFHCore.

**Comment by lazynessmind** [comment] 2021-08-20 11:32
Update:
I asked on discord and a moderator said this.
![image](https://user-images.githubusercontent.com/52864251/130227096-fb6b19d1-0fbc-41e4-9db6-b56a6cfaa5f6.png)

**Comment by Cynix32** [comment] 2021-08-20 17:43
For solution 1, it is simplistic and from the surface level it does seem like the obvious way to go since the purpose of collecting fluids from cows is to use them in crafting recipes. In my case, since Thermal devs intentionally did not make a honey bucket so there would be not much use of a honey bucket in-game if there are no recipes that could use a bucket of honey. Adding a bucket for a fluid that does not originally have a bucket might (not necessarily will) create bugs for the concerned mod. From a programming perspective, solution 1 also seems easier to implement.

Personally, I prefer option 2 since it opens up more possibilities for customization (by manually adding a use for the bucket with the fluid through datapacks/crafttweaker, tho this is already the job of the modpack creator) and the fluid cows can then be used an actually viable alternative source for the fluid in question, such as honey. So that instead of searching for a beehive, it would be viable to capture a fluid cow. This makes gameplay less linear and makes the gameplay a little bit more interesting & fun by providing other ways to acquire resources.

Both solutions are fine for me, so I leave it to your discretion on which would make more sense.

**Comment by lazynessmind** [comment] 2021-08-20 19:09
I have the same opinion on both, that's why I asked you 😅
I may implement the solution 2 with a config to disable generated fluid buckets. I probably have time to upload the new version today on curse.

**Comment by Cynix32** [comment] 2021-08-21 00:46
Fair enough I guess. Implementing the best of both worlds would give the benefits of solution 2 while having a failsafe from option 1 in case any bug/conflict with another mod arises.

**Closed as completed** 2021-12-03 01:31 UTC

**Comment by Cynix32** [comment] 2021-12-06 01:42
Would the fix implemented here be ported to MC 1.16.5?

**Comment by lazynessmind** [comment] 2021-12-06 03:39
Unfortunately not. I originally develop this feature to 1.17 and didn't update it due to lack of time. Now with some time I ported it to 1.18 but isn't viable to backport it to 1.16. Sorry.
